{
  "semi": false,
  "singleQuote": true,
  "jsxSingleQuote": true,
  "tabWidth": 2,
  "printWidth": 100,
  'useTabs': false,
  "quoteProps": "as-needed",
  "trailingComma": "es5",
  "bracketSpacing": false,
  "bracketSameLine": false,
  "arrowParens": "avoid",
  "endOfLine": "auto"
}
